export const ACTION_USER_ADD = 'ACTION_USER_ADD'
export const ACTION_USER_LIST = 'ACTION_USER_LIST'
export const ACTION_USER_LIST_FAIL = 'ACTION_USER_LIST_FAIL'
export const ACTION_USER_UPDATE_ROLE_TYPE = 'ACTION_USER_UPDATE_ROLE_TYPE';